name: Build

on: [push, pull_request]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
#   cancel-in-progress: true

jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wcslib-version: ["8.2.2", "8.3"]
        numpoints: [1000, 10000]
        maxthreads: [5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip
        run: bzcat wcslib-${{ matrix.wcslib-version }}.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: ./configure

      - name: Make wcslib
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: make build

      - name: compile thread race test code
        run: make WCSLIB_VERSION=${{ matrix.wcslib-version }}

      - name: run test with bypass mode
        run: ./test_wcs_threads-bypass ${{ matrix.numpoints }} ${{ matrix.maxthreads }}

      - name: run regular test
        run: ./test_wcs_threads ${{ matrix.numpoints }} ${{ matrix.maxthreads }}

  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: build-on-linux
    strategy:
      matrix:
        wcslib-version: ["8.2.2", "8.3"]

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-openssl

      - name: Install GCC
        run: pacman --noconfirm -S mingw-w64-x86_64-gcc diffutils make

      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip
        run: bzcat wcslib-${{ matrix.wcslib-version }}.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: ./configure

      - name: Make wcslib
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: make build CFLAGS=-DNO_OLDNAMES
        
      - name: compile thread race test code
        run: make WCSLIB_VERSION=${{ matrix.wcslib-version }}

      - name: run test with bypass mode
        run: ./test_wcs_threads-bypass ${{ matrix.numpoints }} ${{ matrix.maxthreads }}

      - name: run regular test
        run: ./test_wcs_threads ${{ matrix.numpoints }} ${{ matrix.maxthreads }}
