name: Build

on:
  workflow_dispatch:

jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unzip
        run: bzcat wcslib-8.1.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.1
        run: ./configure

      - name: Make
        working-directory: wcslib-8.1
        run: make check

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: libwcs
          path: |
            wcslib-8.1/C/libwcs.so.8.1
          retention-days: 3

  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: build-on-linux

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-openssl

      - name: Install GCC
        run: pacman --noconfirm -S gcc diffutils make

      - name: Checkout
        uses: actions/checkout@v3

      - name: Unzip
        run: bzcat wcslib-8.1.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.1
        run: ./configure

      - name: Make
        working-directory: wcslib-8.1
        run: make check

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: libwcs
          path: |
            wcslib-8.1/C/libwcs.dll.8.1
          retention-days: 3
