name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    strategy:   
      matrix:
        wcslib-version: ["8.2.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unzip
        run: bzcat wcslib-${{ matrix.wcslib-version }}.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: ./configure

      - name: Make
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: make build

  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: build-on-linux

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-openssl

      - name: Install GCC
        run: pacman --noconfirm -S mingw-w64-x86_64-gcc diffutils make

      - name: Checkout
        uses: actions/checkout@v3

      - name: Unzip
        run: bzcat wcslib-${{ matrix.wcslib-version }}.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: ./configure

      - name: Make
        working-directory: wcslib-${{ matrix.wcslib-version }}
        run: make build CFLAGS=-DNO_OLDNAMES
